### ISSUE TITLE
Incorrect Language code when using en-AU

### ISSUE THREAD

**Issue by tony-mancini** [amazon-connect/amazon-connect-realtime-transcription#60]
Hi,
I am trying to change the language to Australian (en-AU) but getting an Incorrect language code error in the kvsTranscriber Lambda.
 
Below is the parameters in the Lambda Invocation being sent to the kvsTranscriber Lambda:
{
    "streamARN": "arn:xxxx",
    "startFragmentNum": "xxxx",
    "connectContactId": "xxxxx",
    "transcriptionEnabled": true,
    "saveCallRecording": true,
    "languageCode": "en-AU",
    "streamAudioFromCustomer": true,
    "streamAudioToCustomer": false
}

Below are extracts from the CloudWatch log for the kvsTranscriber execution which shows the code I am passing is correct but is returning an error.

2021-06-10 01:29:50 INFO KVSTranscribeStreamingLambda:95 - received request : streamARN=xxxx, startFragmentNum=xxxx, connectContactId=xxxx, languageCode=Optional[en-AU], transcriptionEnabled=true, saveCallRecording=true, streamAudioFromCustomer=true, streamAudioToCustomer=false

2021-06-10T10:59:50.629+09:30	java.lang.IllegalArgumentException: Incorrect language code
2021-06-10T10:59:50.629+09:30	at com.amazonaws.kvstranscribestreaming.TranscriptionRequest.validate(TranscriptionRequest.java:148)
2021-06-10T10:59:50.629+09:30	at com.amazonaws.kvstranscribestreaming.KVSTranscribeStreamingLambda.handleRequest(KVSTranscribeStreamingLambda.java:100)
2021-06-10T10:59:50.629+09:30	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-06-10T10:59:50.629+09:30	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-06-10T10:59:50.629+09:30	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-06-10T10:59:50.629+09:30	at java.lang.reflect.Method.invoke(Method.java:498)
2021-06-10T10:59:50.629+09:30	at lambdainternal.EventHandlerLoader$PojoMethodRequestHandler.handleRequest(EventHandlerLoader.java:263)
2021-06-10T10:59:50.629+09:30	at lambdainternal.EventHandlerLoader$PojoHandlerAsStreamHandler.handleRequest(EventHandlerLoader.java:180)
2021-06-10T10:59:50.629+09:30	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:902)
2021-06-10T10:59:50.629+09:30	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:340)
2021-06-10T10:59:50.629+09:30	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63)
2021-06-10T10:59:50.629+09:30	at java.lang.Class.forName0(Native Method)
2021-06-10T10:59:50.629+09:30	at java.lang.Class.forName(Class.java:348)
2021-06-10T10:59:50.629+09:30	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150)

**Comment by mcosicaws** [comment]
Could you please check the version of AWS SDK you're using? 
`en-AU` language code was introduced in version `1.11.660`
https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#L8671

Thanks,
Milos

**Comment by mcosicaws** [comment]
Closing due to no response, please feel free to re-open should you need any additional help.
