### ISSUE TITLE
After 3 to 4 minutes I am not getting transcript data.

### ISSUE THREAD

**Issue by vignesLYM** [amazon-connect/amazon-connect-realtime-transcription#62]
Hi Team,

I integrated this feature into my contact center. but after 3 to 4 min only I am getting a response .then after automatically stoping transcribe I am not getting any response from the transcript lambda side. can you please guide me if have any other solution for that?

**Comment by vignesLYM** [comment]
<html>
<body>


2021-08-17T00:00:32.683+05:30 | at com.amazonaws.kvstranscribestreaming.KVSUtils.getByteBufferFromStream(KVSUtils.java:107)
-- | --
  | 2021-08-17T00:00:32.683+05:30 | at com.amazonaws.kvstranscribestreaming.KVSUtils.getByteBufferFromStream(KVSUtils.java:171)
  | 2021-08-17T00:00:32.683+05:30 | at com.amazonaws.transcribestreaming.KVSByteToAudioEventSubscription.lambda$request$0(KVSByteToAudioEventSubscription.java:80)
  | 2021-08-17T00:00:32.683+05:30 | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  | 2021-08-17T00:00:32.683+05:30 | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | 2021-08-17T00:00:32.683+05:30 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | 2021-08-17T00:00:32.683+05:30 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | 2021-08-17T00:00:32.683+05:30 | ... 1 more
  | 2021-08-17T00:00:32.683+05:30Copy2021-08-16 18:30:32 INFO  TranscribeStreamingRetryClient:214 - Reached on error but doing nothingjava.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException | 2021-08-16 18:30:32 INFO TranscribeStreamingRetryClient:214 - Reached on error but doing nothingjava.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException
  | 2021-08-17T00:00:32.683+05:30Copy2021-08-16 18:30:32 DEBUG TranscribeStreamingRetryClient:164 - Error occurred on channel AUDIO_TO_CUSTOMER : software.amazon.awssdk.core.exception.SdkClientException | 2021-08-16 18:30:32 DEBUG TranscribeStreamingRetryClient:164 - Error occurred on channel AUDIO_TO_CUSTOMER : software.amazon.awssdk.core.exception.SdkClientException
  | 2021-08-17T00:00:32.683+05:30 | java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException
  | 2021-08-17T00:00:32.683+05:30 | at software.amazon.awssdk.utils.CompletableFutureUtils.errorAsCompletionException(CompletableFutureUtils.java:61)
  | 2021-08-17T00:00:32.683+05:30Copyat software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.lambda$execute$0(AsyncExecutionFailureExceptionReportingStage.java:50) | at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.lambda$execute$0(AsyncExecutionFailureExceptionReportingStage.java:50)
  | 2021-08-17T00:00:32.683+05:30 | at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
  | 2021-08-17T00:00:32.683+05:30 | at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
  | 2021-08-17T00:00:32.684+05:30 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
  | 2021-08-17T00:00:32.684+05:30 | at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
  | 2021-08-17T00:00:32.684+05:30 | at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.retryErrorIfNeeded(AsyncRetryableStage.java:167)
  | 2021-08-17T00:00:32.684+05:30 | at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.retryIfNeeded(AsyncRetryableStage.java:118)
  | 2021-08-17T00:00:32.684+05:30 | at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.lambda$execute$0(AsyncRetryableStage.java:103)
  | 2021-08-17T00:00:32.684+05:30 | at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
  | 2021-08-17T00:00:32.684+05:30 | at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
  | 2021-08-17T00:00:32.684+05:30 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
  | 2021-08-17T00:00:32.684+05:30 | at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
  | 2021-08-17T00:00:32.684+05:30 | at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage$ResponseHandler.onError(MakeAsyncHttpRequestStage.java:241)
  | 2021-08-17T00:00:32.684+05:30 | at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.handleFailure(NettyRequestExecutor.java:225)
  | 2021-08-17T00:00:32.684+05:30 | at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.lambda$writeRequest$6(NettyRequestExecutor.java:187)
  | 2021-08-17T00:00:32.684+05:30 | at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
  | 2021-08-17T00:00:32.685+05:30 | at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
  | 2021-08-17T00:00:32.685+05:30 | at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:33)
  | 2021-08-17T00:00:32.685+05:30 | at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:435)
  | 2021-08-17T00:00:32.685+05:30 | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
  | 2021-08-17T00:00:32.685+05:30 | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
  | 2021-08-17T00:00:32.685+05:30 | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:474)
  | 2021-08-17T00:00:32.685+05:30 | at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
  | 2021-08-17T00:00:32.685+05:30 | at java.lang.Thread.run(Thread.java:748)
  | 2021-08-17T00:00:32.685+05:30 | Caused by: software.amazon.awssdk.core.exception.SdkClientException
  | 2021-08-17T00:00:32.685+05:30 | at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:97)
  | 2021-08-17T00:00:32.685+05:30 | at software.amazon.awssdk.core.internal.util.ThrowableUtils.asSdkException(ThrowableUtils.java:98)
  | 2021-08-17T00:00:32.686+05:30 | at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.retryIfNeeded(AsyncRetryableStage.java:117)
  | 2021-08-17T00:00:32.686+05:30 | ... 17 more
  | 2021-08-17T00:00:32.702+05:30CopyCaused by: java.lang.IllegalArgumentException: Trying to decode an EBML ID and it wants 7 more bytes, but IDs max out at 4 bytes. firstByte was 1 | Caused by: java.lang.IllegalArgumentException: Trying to decode an EBML ID and it wants 7 more bytes, but IDs max out at 4 bytes. firstByte was 1
  | 2021-08-17T00:00:32.702+05:30 | at org.apache.commons.lang3.Validate.isTrue(Validate.java:158)
  | 2021-08-17T00:00:32.702+05:30 | at com.amazonaws.kinesisvideo.parser.ebml.EBMLUtils.readId(EBMLUtils.java:62)
  | 2021-08-17T00:00:32.702+05:30 | at com.amazonaws.kinesisvideo.parser.ebml.EBMLParserInternalElement.readId(EBMLParserInternalElement.java:48)
  | 2021-08-17T00:00:32.702+05:30 | at com.amazonaws.kinesisvideo.parser.ebml.EBMLParser.parse(EBMLParser.java:85)
  | 2021-08-17T00:00:32.702+05:30 | at com.amazonaws.kinesisvideo.parser.mkv.StreamingMkvReader.nextIfAvailable(StreamingMkvReader.java:116)
  | 2021-08-17T00:00:32.702+05:30 | at com.amazonaws.kvstranscribestreaming.KVSUtils.getByteBufferFromStream(KVSUtils.java:107)
  | 2021-08-17T00:00:32.702+05:30 | at com.amazonaws.kvstranscribestreaming.KVSUtils.getByteBufferFromStream(KVSUtils.java:171)
  | 2021-08-17T00:00:32.702+05:30 | at com.amazonaws.transcribestreaming.KVSByteToAudioEventSubscription.lambda$request$0(KVSByteToAudioEventSubscription.java:80)
  | 2021-08-17T00:00:32.702+05:30 | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  | 2021-08-17T00:00:32.702+05:30 | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | 2021-08-17T00:00:32.702+05:30 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | 2021-08-17T00:00:32.702+05:30 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | 2021-08-17T00:00:32.703+05:30 | ... 1 more
  | 2021-08-17T00:00:33.013+05:30 | 2021-08-16 18:30:33 INFO TranscribeStreamingRetryClient:218 - Reached on complete.
  | 2021-08-17T00:00:33.024+05:30 | 2021-08-16 18:30:33 INFO TranscribeStreamingRetryClient:218 - Reached on complete.
  | 2021-08-17T00:10:21.888+05:30 | 2021-08-16 18:40:21 DEBUG TranscribeStreamingRetryClient:248 - TranscribeStreamingRetryClient closed
  | 2021-08-17T00:10:21.888+05:30 | 2021-08-16 18:40:21 DEBUG KVSTranscribeStreamingLambda:184 - Timing out KVS to Transcribe Streaming after 890 sec
  | 2021-08-17T00:10:21.909+05:30 | 2021-08-16 18:40:21 ERROR KVSTranscribeStreamingLambda:124 - KVS to Transcribe Streaming failed with:
  | 2021-08-17T00:10:21.909+05:30 | java.net.SocketException: Connection reset
  | 2021-08-17T00:10:21.909+05:30 | at java.net.SocketInputStream.read(SocketInputStream.java:210)
  | 2021-08-17T00:10:21.909+05:30 | at java.net.SocketInputStream.read(SocketInputStream.java:141)
  | 2021-08-17T00:10:21.909+05:30 | at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
  | 2021-08-17T00:10:21.909+05:30 | at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
  | 2021-08-17T00:10:21.909+05:30 | at sun.security.ssl.InputRecord.read(InputRecord.java:532)
  | 2021-08-17T00:10:21.909+05:30 | at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
  | 2021-08-17T00:10:21.909+05:30 | at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
  | 2021-08-17T00:10:21.909+05:30 | at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
  | 2021-08-17T00:10:21.909+05:30 | at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
  | 2021-08-17T00:10:21.909+05:30 | at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
  | 2021-08-17T00:10:21.909+05:30 | at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
  | 2021-08-17T00:10:21.909+05:30 | at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:261)
  | 2021-08-17T00:10:21.909+05:30 | at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:222)
  | 2021-08-17T00:10:21.909+05:30 | at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:183)
  | 2021-08-17T00:10:21.909+05:30 | at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:210)
  | 2021-08-17T00:10:21.909+05:30 | at org.apache.http.impl.io.ChunkedInputStream.close(ChunkedInputStream.java:312)
  | 2021-08-17T00:10:21.909+05:30 | at org.apache.http.impl.execchain.ResponseEntityProxy.streamClosed(ResponseEntityProxy.java:142)
  | 2021-08-17T00:10:21.909+05:30 | at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)
  | 2021-08-17T00:10:21.909+05:30 | at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:172)
  | 2021-08-17T00:10:21.909+05:30 | at com.amazonaws.internal.SdkFilterInputStream.close(SdkFilterInputStream.java:107)
  | 2021-08-17T00:10:21.909+05:30 | at com.amazonaws.event.ProgressInputStream.close(ProgressInputStream.java:211)
  | 2021-08-17T00:10:21.909+05:30 | at com.amazonaws.internal.SdkFilterInputStream.close(SdkFilterInputStream.java:107)
  | 2021-08-17T00:10:21.909+05:30Copyat com.amazonaws.kvstranscribestreaming.KVSTranscribeStreamingLambda.closeFileAndUploadRawAudio(KVSTranscribeStreamingLambda.java:274) | at com.amazonaws.kvstranscribestreaming.KVSTranscribeStreamingLambda.closeFileAndUploadRawAudio(KVSTranscribeStreamingLambda.java:274)
  | 2021-08-17T00:10:21.909+05:30 | at com.amazonaws.kvstranscribestreaming.KVSTranscribeStreamingLambda.startKVSToTranscribeStreaming(KVSTranscribeStreamingLambda.java:192)
  | 2021-08-17T00:10:21.909+05:30 | at com.amazonaws.kvstranscribestreaming.KVSTranscribeStreamingLambda.handleRequest(KVSTranscribeStreamingLambda.java:116)
  | 2021-08-17T00:10:21.909+05:30 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | 2021-08-17T00:10:21.909+05:30 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | 2021-08-17T00:10:21.909+05:30 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | 2021-08-17T00:10:21.909+05:30 | at java.lang.reflect.Method.invoke(Method.java:498)
  | 2021-08-17T00:10:21.909+05:30 | at lambdainternal.EventHandlerLoader$PojoMethodRequestHandler.handleRequest(EventHandlerLoader.java:263)
  | 2021-08-17T00:10:21.909+05:30 | at lambdainternal.EventHandlerLoader$PojoHandlerAsStreamHandler.handleRequest(EventHandlerLoader.java:180)
  | 2021-08-17T00:10:21.909+05:30 | at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:902)
  | 2021-08-17T00:10:21.909+05:30 | at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:340)
  | 2021-08-17T00:10:21.909+05:30 | at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63)
  | 2021-08-17T00:10:21.909+05:30 | at java.lang.Class.forName0(Native Method)
  | 2021-08-17T00:10:21.909+05:30 | at java.lang.Class.forName(Class.java:348)
  | 2021-08-17T00:10:21.909+05:30 | at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150)
  | 2021-08-17T00:10:21.915+05:30 | END RequestId: 984fac2e-c540-4737-bab5-e23dddc30977
  | 2021-08-17T00:10:21.915+05:30 | REPORT RequestId: 984fac2e-c540-4737-bab5-e23dddc30977 Duration: 890304.51 ms Billed Duration: 890305 ms Memory Si


</body>
</html>

**Comment by vignesLYM** [comment]
2021-08-17T00:00:32.683+05:30	at com.amazonaws.kvstranscribestreaming.KVSUtils.getByteBufferFromStream(KVSUtils.java:107)

2021-08-17T00:00:32.683+05:30	at com.amazonaws.kvstranscribestreaming.KVSUtils.getByteBufferFromStream(KVSUtils.java:171)

2021-08-17T00:00:32.683+05:30	at com.amazonaws.transcribestreaming.KVSByteToAudioEventSubscription.lambda$request$0(KVSByteToAudioEventSubscription.java:80)

2021-08-17T00:00:32.683+05:30	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

2021-08-17T00:00:32.683+05:30	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

2021-08-17T00:00:32.683+05:30	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

2021-08-17T00:00:32.683+05:30	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

2021-08-17T00:00:32.683+05:30	... 1 more

2021-08-17T00:00:32.683+05:30

Copy
2021-08-16 18:30:32 INFO  TranscribeStreamingRetryClient:214 - Reached on error but doing nothingjava.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException
2021-08-16 18:30:32 INFO TranscribeStreamingRetryClient:214 - Reached on error but doing nothingjava.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException

2021-08-17T00:00:32.683+05:30

Copy
2021-08-16 18:30:32 DEBUG TranscribeStreamingRetryClient:164 - Error occurred on channel AUDIO_TO_CUSTOMER : software.amazon.awssdk.core.exception.SdkClientException
2021-08-16 18:30:32 DEBUG TranscribeStreamingRetryClient:164 - Error occurred on channel AUDIO_TO_CUSTOMER : software.amazon.awssdk.core.exception.SdkClientException

2021-08-17T00:00:32.683+05:30	java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException

2021-08-17T00:00:32.683+05:30	at software.amazon.awssdk.utils.CompletableFutureUtils.errorAsCompletionException(CompletableFutureUtils.java:61)

2021-08-17T00:00:32.683+05:30

Copy
at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.lambda$execute$0(AsyncExecutionFailureExceptionReportingStage.java:50)
at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.lambda$execute$0(AsyncExecutionFailureExceptionReportingStage.java:50)

2021-08-17T00:00:32.683+05:30	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)

2021-08-17T00:00:32.683+05:30	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)

2021-08-17T00:00:32.684+05:30	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)

2021-08-17T00:00:32.684+05:30	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)

2021-08-17T00:00:32.684+05:30	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.retryErrorIfNeeded(AsyncRetryableStage.java:167)

2021-08-17T00:00:32.684+05:30	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.retryIfNeeded(AsyncRetryableStage.java:118)

2021-08-17T00:00:32.684+05:30	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.lambda$execute$0(AsyncRetryableStage.java:103)

2021-08-17T00:00:32.684+05:30	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)

2021-08-17T00:00:32.684+05:30	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)

2021-08-17T00:00:32.684+05:30	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)

2021-08-17T00:00:32.684+05:30	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)

2021-08-17T00:00:32.684+05:30	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage$ResponseHandler.onError(MakeAsyncHttpRequestStage.java:241)

2021-08-17T00:00:32.684+05:30	at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.handleFailure(NettyRequestExecutor.java:225)

2021-08-17T00:00:32.684+05:30	at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.lambda$writeRequest$6(NettyRequestExecutor.java:187)

2021-08-17T00:00:32.684+05:30	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)

2021-08-17T00:00:32.685+05:30	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)

2021-08-17T00:00:32.685+05:30	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:33)

2021-08-17T00:00:32.685+05:30	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:435)

2021-08-17T00:00:32.685+05:30	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)

2021-08-17T00:00:32.685+05:30	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)

2021-08-17T00:00:32.685+05:30	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:474)

2021-08-17T00:00:32.685+05:30	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)

2021-08-17T00:00:32.685+05:30	at java.lang.Thread.run(Thread.java:748)

2021-08-17T00:00:32.685+05:30	Caused by: software.amazon.awssdk.core.exception.SdkClientException

2021-08-17T00:00:32.685+05:30	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:97)

2021-08-17T00:00:32.685+05:30	at software.amazon.awssdk.core.internal.util.ThrowableUtils.asSdkException(ThrowableUtils.java:98)

2021-08-17T00:00:32.686+05:30	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.retryIfNeeded(AsyncRetryableStage.java:117)

2021-08-17T00:00:32.686+05:30	... 17 more

2021-08-17T00:00:32.702+05:30

Copy
Caused by: java.lang.IllegalArgumentException: Trying to decode an EBML ID and it wants 7 more bytes, but IDs max out at 4 bytes. firstByte was 1
Caused by: java.lang.IllegalArgumentException: Trying to decode an EBML ID and it wants 7 more bytes, but IDs max out at 4 bytes. firstByte was 1

2021-08-17T00:00:32.702+05:30	at org.apache.commons.lang3.Validate.isTrue(Validate.java:158)

2021-08-17T00:00:32.702+05:30	at com.amazonaws.kinesisvideo.parser.ebml.EBMLUtils.readId(EBMLUtils.java:62)

2021-08-17T00:00:32.702+05:30	at com.amazonaws.kinesisvideo.parser.ebml.EBMLParserInternalElement.readId(EBMLParserInternalElement.java:48)

2021-08-17T00:00:32.702+05:30	at com.amazonaws.kinesisvideo.parser.ebml.EBMLParser.parse(EBMLParser.java:85)

2021-08-17T00:00:32.702+05:30	at com.amazonaws.kinesisvideo.parser.mkv.StreamingMkvReader.nextIfAvailable(StreamingMkvReader.java:116)

2021-08-17T00:00:32.702+05:30	at com.amazonaws.kvstranscribestreaming.KVSUtils.getByteBufferFromStream(KVSUtils.java:107)

2021-08-17T00:00:32.702+05:30	at com.amazonaws.kvstranscribestreaming.KVSUtils.getByteBufferFromStream(KVSUtils.java:171)

2021-08-17T00:00:32.702+05:30	at com.amazonaws.transcribestreaming.KVSByteToAudioEventSubscription.lambda$request$0(KVSByteToAudioEventSubscription.java:80)

2021-08-17T00:00:32.702+05:30	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

2021-08-17T00:00:32.702+05:30	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

2021-08-17T00:00:32.702+05:30	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

2021-08-17T00:00:32.702+05:30	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

2021-08-17T00:00:32.703+05:30	... 1 more

2021-08-17T00:00:33.013+05:30	2021-08-16 18:30:33 INFO TranscribeStreamingRetryClient:218 - Reached on complete.

2021-08-17T00:00:33.024+05:30	2021-08-16 18:30:33 INFO TranscribeStreamingRetryClient:218 - Reached on complete.

2021-08-17T00:10:21.888+05:30	2021-08-16 18:40:21 DEBUG TranscribeStreamingRetryClient:248 - TranscribeStreamingRetryClient closed

2021-08-17T00:10:21.888+05:30	2021-08-16 18:40:21 DEBUG KVSTranscribeStreamingLambda:184 - Timing out KVS to Transcribe Streaming after 890 sec

2021-08-17T00:10:21.909+05:30	2021-08-16 18:40:21 ERROR KVSTranscribeStreamingLambda:124 - KVS to Transcribe Streaming failed with:

2021-08-17T00:10:21.909+05:30	java.net.SocketException: Connection reset

2021-08-17T00:10:21.909+05:30	at java.net.SocketInputStream.read(SocketInputStream.java:210)

2021-08-17T00:10:21.909+05:30	at java.net.SocketInputStream.read(SocketInputStream.java:141)

2021-08-17T00:10:21.909+05:30	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)

2021-08-17T00:10:21.909+05:30	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)

2021-08-17T00:10:21.909+05:30	at sun.security.ssl.InputRecord.read(InputRecord.java:532)

2021-08-17T00:10:21.909+05:30	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)

2021-08-17T00:10:21.909+05:30	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)

2021-08-17T00:10:21.909+05:30	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)

2021-08-17T00:10:21.909+05:30	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)

2021-08-17T00:10:21.909+05:30	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)

2021-08-17T00:10:21.909+05:30	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)

2021-08-17T00:10:21.909+05:30	at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:261)

2021-08-17T00:10:21.909+05:30	at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:222)

2021-08-17T00:10:21.909+05:30	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:183)

2021-08-17T00:10:21.909+05:30	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:210)

2021-08-17T00:10:21.909+05:30	at org.apache.http.impl.io.ChunkedInputStream.close(ChunkedInputStream.java:312)

2021-08-17T00:10:21.909+05:30	at org.apache.http.impl.execchain.ResponseEntityProxy.streamClosed(ResponseEntityProxy.java:142)

2021-08-17T00:10:21.909+05:30	at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)

2021-08-17T00:10:21.909+05:30	at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:172)

2021-08-17T00:10:21.909+05:30	at com.amazonaws.internal.SdkFilterInputStream.close(SdkFilterInputStream.java:107)

2021-08-17T00:10:21.909+05:30	at com.amazonaws.event.ProgressInputStream.close(ProgressInputStream.java:211)

2021-08-17T00:10:21.909+05:30	at com.amazonaws.internal.SdkFilterInputStream.close(SdkFilterInputStream.java:107)

2021-08-17T00:10:21.909+05:30

Copy
at com.amazonaws.kvstranscribestreaming.KVSTranscribeStreamingLambda.closeFileAndUploadRawAudio(KVSTranscribeStreamingLambda.java:274)
at com.amazonaws.kvstranscribestreaming.KVSTranscribeStreamingLambda.closeFileAndUploadRawAudio(KVSTranscribeStreamingLambda.java:274)

2021-08-17T00:10:21.909+05:30	at com.amazonaws.kvstranscribestreaming.KVSTranscribeStreamingLambda.startKVSToTranscribeStreaming(KVSTranscribeStreamingLambda.java:192)

2021-08-17T00:10:21.909+05:30	at com.amazonaws.kvstranscribestreaming.KVSTranscribeStreamingLambda.handleRequest(KVSTranscribeStreamingLambda.java:116)

2021-08-17T00:10:21.909+05:30	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

2021-08-17T00:10:21.909+05:30	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

2021-08-17T00:10:21.909+05:30	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

2021-08-17T00:10:21.909+05:30	at java.lang.reflect.Method.invoke(Method.java:498)

2021-08-17T00:10:21.909+05:30	at lambdainternal.EventHandlerLoader$PojoMethodRequestHandler.handleRequest(EventHandlerLoader.java:263)

2021-08-17T00:10:21.909+05:30	at lambdainternal.EventHandlerLoader$PojoHandlerAsStreamHandler.handleRequest(EventHandlerLoader.java:180)

2021-08-17T00:10:21.909+05:30	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:902)

2021-08-17T00:10:21.909+05:30	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:340)

2021-08-17T00:10:21.909+05:30	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:63)

2021-08-17T00:10:21.909+05:30	at java.lang.Class.forName0(Native Method)

2021-08-17T00:10:21.909+05:30	at java.lang.Class.forName(Class.java:348)

2021-08-17T00:10:21.909+05:30	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150)

2021-08-17T00:10:21.915+05:30	END RequestId: 984fac2e-c540-4737-bab5-e23dddc30977

2021-08-17T00:10:21.915+05:30	REPORT RequestId: 984fac2e-c540-4737-bab5-e23dddc30977 Duration: 890304.51 ms Billed Duration: 890305 ms Memory Si

**Comment by UrielSaltoOroz** [comment]
@vignesLYM I have the same problem, can you help me to resolved it?

Thanks in advance.
